# Generated by Django 3.1.2 on 2020-10-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201027_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
