# Generated by Django 3.1.2 on 2020-10-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.URLField(blank=True),
        ),
    ]
